name: Feature Request
about: Suggest an improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
